
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Izbornik</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="top-bar" id="responsive-menu">
  <div class="top-bar-left">
    <ul class="dropdown menu" data-dropdown-menu>
      <li>
        <a href="<?php echo APP::config("url") ?>">
            <?php echo APP::config("nazivApp"); ?>
        </a>
      </li>
      <li>
        <a href="<?php echo APP::config("url") ?>index/onama">O nama</a>
      </li>
      <li>
        <a href="<?php echo APP::config("url") ?>index/kontakt">Kontakt</a>
      </li> 
    </ul>
  </div>
  
  </div>
</nav>